### ISSUE TITLE
BDD syntax - use scenario/feature files

### ISSUE THREAD

**Issue by robertlagrant** [nikoheikkila/playwright-kickstarter#3]
Thanks for the very well-structured repo. I'm trying to use BDD techniques such as writing scenarios and features in feature files and glueing them to Playwright code behind the scenes via Cucumber. I use this template: https://github.com/e2e-boilerplate/playwright-commonjs-cucumber-expect. This works fairly well, but not having Playwright in charge of how the tests are run reduces some of the power of it.

Is it possible to extend this repo to get Playwright to support the full Cucumber-like experience without handing over the CucumberJS the overall control over when tests are run?

**Comment by nikoheikkila** [comment]
Hi @robertlagrant!

That's a good question. I've been thinking about it myself as well. But, unfortunately, the closest I have got is with the `test.describe()` and `test()` blocks, which are still not pure Gherkin and, of course, aren't in sync with your feature files.

One solution I'd like to see is adding a feature to Playwright CLI that allows you to read `*.feature` files, generate `@playwright/test` compliant test code from these for developers to fill in, and then run the tests. It's similar to how the `pytest-bdd` package works in the Python world.

**Comment by robertlagrant** [comment]
Hi @nikoheikkila thanks for the great response. I think you're right; that would be a great way to close the gap between the two worlds.
